apiVersion: v1
kind: Service
metadata:
  name: sample-svc
  labels:
    name: sample
    app: java
spec:
  selector:
    app: java
  type: NodePort
  ports:
   - port: 8080
     targetPort: 8080 
     protocol: TCP
     nodePort: 30095
